name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  Test:
    strategy:
      fail-fast: false
      matrix:
        go: [ '1.22', '1.21' ]
    uses: bytemare/workflows/.github/workflows/test-go.yml@3cd1aa75e8e961604ce127de3a1dfd50eb555931
    with:
      command: cd .github && make test
      version: ${{ matrix.go }}
